apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-nodeapp
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: miapp-prod-keyvault
    objects: |
      array:
        - objectName: MONGODB_URI
          objectType: secret
        - objectName: PORT
          objectType: secret
    tenantId: TU_TENANT_ID
  secretObjects:
    - secretName: kv-secrets
      type: Opaque
      data:
        - objectName: MONGODB_URI
          key: MONGODB_URI
        - objectName: PORT
          key: PORT
